---
group: deprecated-2017Q2
sudo: required
dist: trusty

language: python
python: "2.7"


branches:
  only:
    - master

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/